# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

##===> Opacity & Blur
############################################
windowrulev2 = noblur, class:^$
windowrulev2 = opacity 0.90 0.90, class:^.*$
windowrulev2 = opacity 1.0 1.0, class:^(firefox)$

##===> Picture In Picture
############################################
windowrulev2 = float, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrulev2 = pin, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$

##===> idleinhibit rules
############################################
windowrulev2 = idleinhibit fullscreen, class:^(.*celluloid.*)$|^(.*mpv.*)$|^(.*vlc.*)$
windowrulev2 = idleinhibit fullscreen, class:^(.*[Ss]potify.*)$
windowrulev2 = idleinhibit fullscreen, class:^(yandex-music)$
windowrulev2 = idleinhibit fullscreen, class:^(.*LibreWolf.*)$|^(.*floorp.*)$|^(.*brave-browser.*)$|^(.*firefox.*)$|^(.*chromium.*)$|^(.*zen.*)$|^(.*vivaldi.*)$

##===> Floating windows
############################################
windowrulev2 = float, class:^(vlc)$
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(firefox)$, title:^(Picture-in-Picture)$
windowrulev2 = float, class:^(firefox)$, title:^(Library)$
windowrulev2 = float, class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = float, class:^(qt5ct)$
windowrulev2 = float, class:^(qt6ct)$
windowrulev2 = float, class:^(org.kde.ark)$
windowrulev2 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = float, class:^(yad)$
windowrulev2 = float, class:^(gnome-calculator)$
windowrulev2 = float, class:^(org.gnome.Loupe)$
windowrulev2 = float, class:^(org.gnome.FileRoller)$
windowrulev2 = float, class:^(com.meowrch.HotkeyHub)$
windowrulev2 = float, class:^(qalculate-gtk)$

# modals
windowrulev2 = float, title:^(Open)$
windowrulev2 = float, title:^(Authentication Required)$
windowrulev2 = float, title:^(Add Folder to Workspace)$
windowrulev2 = float, title:^(Open File)$
windowrulev2 = float, title:^(Choose Files)$
windowrulev2 = float, title:^(Save As)$
windowrulev2 = float, title:^(Confirm to replace files)$
windowrulev2 = float, title:^(File Operation Progress)$
windowrulev2 = float, title:^(File Upload)(.*)$
windowrulev2 = float, title:^(Choose wallpaper)(.*)$
windowrulev2 = float, title:^(Library)(.*)$
windowrulev2 = float, class:^(.*dialog.*)$
windowrulev2 = float, title:^(.*dialog.*)$

# hyprland portal
windowrulev2 = float, class:^(org.freedesktop.impl.portal.desktop.hyprland)$

# gtk portal
windowrulev2 = float, class:^(org.freedesktop.impl.portal.desktop.gtk)$

# xdg-desktop-portal-gtk
windowrulev2 = float, class:^([Xx]dg-desktop-portal-gtk)$

##===> Layer rules
############################################
layerrule = blur, rofi
layerrule = ignorealpha 0, rofi
layerrule = blur, notifications
layerrule = ignorealpha 0, notifications
layerrule = blur, waybar
