# █░█ █▄█ █▀█ █▀█ █░░ ▄▀█ █▄░█ █▀▄
# █▀█ ░█░ █▀▀ █▀▄ █▄▄ █▀█ █░▀█ █▄▀

$meowrch = $HOME/.config/meowrch/meowrch.py


# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

# See https://wiki.hyprland.org/Configuring/Keywords/

# Core components are handled in autostart.conf using uwsm-launcher.sh
# or by NixOS systemd services.


# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24
exec-once = hyprctl setcursor Bibata-Modern-Classic 24


# █▀ █▀█ █░█ █▀█ █▀▀ █▀▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄

source = ~/.config/hypr/default/autostart.conf
source = ~/.config/hypr/default/monitors.conf
source = ~/.config/hypr/default/input.conf
source = ~/.config/hypr/default/keybindings.conf
source = ~/.config/hypr/default/windowrules.conf
source = ~/.config/hypr/default/appearance.conf
source = ~/.config/hypr/default/general.conf
source = ~/.config/hypr/userprefs.conf

# Dynamic Meowrch Theme (NixOS-friendly)
source = ~/.cache/meowrch/hypr/theme.conf

# Mewline
source = ~/.config/hypr/mewline.conf
