# █▀ █▀█ █▀▀ █▀▀ █ ▄▀█ █░░
# ▄█ █▀▀ ██▄ █▄▄ █ █▀█ █▄▄

# Theme configuration (decoration & appearance)

decoration {
    dim_special = 0.3
    rounding = 10

    blur {
        special = true
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

# Custom prefs from meowrch theme (general section with gaps, borders, etc.)
source = ~/.config/hypr/custom-prefs.conf