##==> Set your personal hyprland configuration here
#############################################################################

##==> Optimization for your operating mode (default.conf / powersaver.conf / gaming.conf)
#######################################
source = ~/.config/hypr/workflows/default.conf

##==> IO
#######################################

monitor = ,preferred,auto,1

input {
    kb_layout = us,ru
    kb_options = grp:caps_toggle
    numlock_by_default = true
    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = no
    }
}

##==> Hotkeys
#######################################
bind = Super+Shift, C, exec, code
bind = Super+Shift, F, exec, firefox
bind = Super+Shift, T, exec, Telegram
bind = Super+Shift, O, exec, obsidian
bind = Super+Shift, P, exec, pavucontrol
bind = Super+Shift, Y, exec, kitty -e yazi

##==> Decorations
#############################d##########
decoration {
    # screen_shader = ~/.config/hypr/shaders/rounded_corners.glsl
}
