# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "uas" "sd_mod" ];
  boot.initrd.kernelModules = ["i915"];
   boot.kernelModules = [
    "kvm-intel"
    "drm"
    "drm_kms_helper"
  ];
  boot.extraModulePackages = [ ];

  # i915 GuC + runtime/power params
  boot.kernelParams = [
    "i915.enable_guc=3"
    "i915.fastboot=1"
    "i915.enable_rc6=1"
    "i915.enable_dc=1"
    "i915.enable_psr=1"
  ];

  ############################################
  # vm maps
  ############################################
  boot.kernel.sysctl = {
    "vm.max_map_count" = 262144;
  };


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/70a764a4-86fb-4842-a97f-8ffc86a65838";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/483F-365D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

############################################
  # X11 video driver (if X is enabled)
  ############################################
  services.xserver.videoDrivers = lib.mkIf config.services.xserver.enable [ "modesetting" ];

  ############################################
  # Graphics stack with 32-bit support
  ############################################
  hardware.graphics = {
    enable = true;
    enable32Bit = true;

    extraPackages = lib.concatLists [
      (with pkgs; [
        mesa
        libva
        libva-utils
        libdrm
        vulkan-loader
        vulkan-tools
        vulkan-validation-layers
        vulkan-extension-layer
        intel-media-driver
        intel-vaapi-driver
        libva-vdpau-driver
        libvdpau-va-gl
        vpl-gpu-rt
      ])
      (if builtins.hasAttr "vulkan-intel" pkgs then [ pkgs.vulkan-intel ] else [ ])
    ];

    # Avoid pulling a second mesa copy. Leave empty unless you need specific 32-bit libs.
    extraPackages32 = [ ];
  };

  ############################################
  # Environment variables to prefer iris userspace driver
  ############################################
  environment.sessionVariables = {
    LIBVA_DRIVER_NAME = "iHD";
    VAAPI_DRIVERS_PATH = "/run/opengl-driver/lib/dri";
    MESA_LOADER_DRIVER_OVERRIDE = "iris";
  };

  ############################################
  # Scanner support
  ############################################
  hardware.sane = {
    enable = true;
    extraBackends = with pkgs; [
      hplip
      sane-airscan
    ];
  };

  ############################################
  # Common userland tooling / diagnostics
  ############################################
  environment.systemPackages = with pkgs; [
    linux-firmware
    microcode-intel
    vulkan-tools
    glmark2

    # Mesa demos (glxinfo) and VA-API utils (vainfo)
    mesa-demos
    libva-utils

    # Wayland utilities
    wlr-randr
    wayland-utils
    # Debugging & tracing
    renderdoc
    apitrace

    # Development libs
    libGL
    libGLU
    wayland
    wayland-protocols

    # Hyprland / wlroots helper libs
    seatd
    libinput
    libxkbcommon
    xorg.libxcb
    pipewire
    libgbm

    # Intel-specific monitoring tools
    intel-gpu-tools
  ];

  ############################################
  # Runtime tmpfiles
  ############################################
  systemd.tmpfiles.rules = [
    "d /tmp/.X11-unix 1777 root root 10d"
    "d /tmp/.ICE-unix 1777 root root 10d"
  ];

  ############################################
  # Hardware configuration
  ############################################
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
